### ISSUE TITLE
Error: Parse Error when trying to run the test file

### ISSUE THREAD

**Issue by nanthakumarv** [paypal/nemo-accessibility#12]
hi @mpnkhan ,

I am trying to implement this nemo-accessibility for my project. I have given the following in the config file 
{
  "driver": {
    "browser": "firefox"
  },
  "plugins": {
    "nemo-accessibility": {
      "module": "path:../",
      "arguments": ["http://127.0.0.1:8081/evaluate"]
    },
    "view": {
      "module": "nemo-view"
    }    
  }
}

And when i try to run usingNemoAccessibility.js, getting the below error:

$ node example/usingNemoAccessibility.js
Nemo initialized successfully
C:\Users\391533\nemo-accessibility\node_modules\selenium-webdriver\lib\goog\asyn
c\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^

Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:359:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)

I am new to this testing, can you please help me out to solve this issue?

**Comment by nanthakumarv** [comment]
@mpnkhan 

And sometimes i also get a different error:

$ node example/usingNemoAccessibility.js
Nemo initialized successfully

C:\Users\391533\nemo-accessibility\node_modules\selenium-webdriver\lib\goog\asyn
c\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^
 Error is null Response code is 400

**Comment by mpnkhan** [comment]
Can you try using chrome as browser?   You have to download latest chrome driver and set the  directory in path or download to default location
https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver

**Comment by nikulkarni** [comment]
If @mpnkhan's suggestion is not working for you, please provide versions of  nemo and node

**Comment by nanthakumarv** [comment]
@mpnkhan , @nikulkarni 

Thanks for your update. I set the chromedriver path in my environment variable properly and changed the browser to chrome in my config file. Then i ran the test. But it says, chromedriver path not found.
I have given the proper chromedriver path only.

Should we give some webdriver initialization code? If so where should we provide them? should we provide it in the test file or in the config file? Kindly help.

**Comment by nanthakumarv** [comment]
@mpnkhan ,@nikulkarni

This is the error which i am getting now

$ node example/usingNemoAccessibility.js --BROWSER=chrome
C:\Users\391533\nemo-accessibility\example\usingNemoAccessibility.js:7
          WebDriver driver = new ChromeDriver();
                    ^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3

**Comment by nanthakumarv** [comment]
HI @mpnkhan & @nikulkarni 

I have resolved this issue with the chromedriver, now the UI is being launched in the chrome browser but the error is thrown while scanning.

But now we are seeing different issues while testing with different websites. Please help with resolving this issues.

When using Paypal.com for testing, getting the below error:
$ node example/usingNemoAccessibility.js
Nemo initialized successfully
[0308/192039.867:ERROR:mf_helpers.cc(12)] Error in dxva_video_decode_accelerator_win.cc on line 345
C:\Users\391533\nemo-accessibility\node_modules\selenium-webdriver\lib\goog\async\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^
Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:359:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)

When using google.com for testing, getting the below error:
$ node example/usingNemoAccessibility.js
Nemo initialized successfully
C:\Users\391533\nemo-accessibility\node_modules\selenium-webdriver\lib\goog\async\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^

Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:359:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)

When using the gmail.com for testing, getting the below error
$ node example/usingNemoAccessibility.js
Nemo initialized successfully
C:\Users\391533\nemo-accessibility\node_modules\selenium-webdriver\lib\goog\async\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:949:11)
    at TCP.onread (net.js:563:26)

Please help to overcome this issue.

Thanks,
Vithushini
