### ISSUE TITLE
TypeError: driver.executeScript is not a function

### ISSUE THREAD

**Issue by rkrjain** [paypal/nemo-accessibility#17]
I have been struggling with this issue for quite long now. I am trying to run the test on a particular element using the nemo_view plugin.

I get this error continuously --- 

```
1) nemo-view will run scan on a modal:
     TypeError: driver.executeScript is not a function
      at Object.scan (D:\UI PRAC\AATT\aatt_nemo\nemo-accessibility\index.js:116:20)
      at Context.<anonymous> (D:\UI PRAC\AATT\aatt_nemo\nemo-accessibility\test\formSpec.js:64:28)
      at callFnAsync (D:\UI PRAC\AATT\aatt_nemo\nemo-accessibility\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (D:\UI PRAC\AATT\aatt_nemo\nemo-accessibility\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (D:\UI PRAC\AATT\aatt_nemo\nemo-accessibility\node_modules\mocha\lib\runner.js:422:10)
      at D:\UI PRAC\AATT\aatt_nemo\nemo-accessibility\node_modules\mocha\lib\runner.js:528:12
      at next (D:\UI PRAC\AATT\aatt_nemo\nemo-accessibility\node_modules\mocha\lib\runner.js:342:14)
      at D:\UI PRAC\AATT\aatt_nemo\nemo-accessibility\node_modules\mocha\lib\runner.js:352:7
      at next (D:\UI PRAC\AATT\aatt_nemo\nemo-accessibility\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (D:\UI PRAC\AATT\aatt_nemo\nemo-accessibility\node_modules\mocha\lib\runner.js:320:5)
```
I have done a lot of trial & errors but all in vain. Need help in getting this running.

I was able to run the page-level test with success. But the element level scan is not working.

This is what I am trying

```
    it('will run scan on a modal', function (done) {
        nemo.driver.get(nemo.data.urls.home);

        var element = nemo.view.modal.myModal();
        // var element = nemo.view._find('css:#myModal');
        var options = {
            'priority': ['P1', 'P2'],
            'element': element,
            'engine': 'htmlcs'
        };
        nemo.accessibility.scan(options).then(function (result) {
            fs.writeFile(process.cwd() + '/app_test/report/modal.html', result, function (err) {
                done();
            });
        });
    });
```

my config
```
{
    "driver": {
        "browser": "phantomjs"
    },
    "plugins": {
        "nemo-accessibility": {
            "module": "path:../",
            "arguments": [
                {
                    "accessibilityApiUrl": "http://localhost:3000/evaluate",
                    "engine": "chrome"
                }
            ]
        },
        "view": {
            "module": "nemo-view",
            "arguments": ["path:../locator"]
        }
    },
    "data": {
        "urls": {
            "home": "http://localhost:8000"
        }
    }
}
```

my nemo_view locator

```
{
    "myModal": {
        "locator": "#myModal",
        "type": "css"
    }
}
```

**Comment by rkrjain** [comment]
Any help on this issue. I am stuck at this point, not able to proceed

**Comment by mpnkhan** [comment]
Working on this, give us some time. sorry.
What version of this plugin you use?

**Comment by mpnkhan** [comment]
Have done some code changes, could you kindly check if this working?

https://github.com/paypal/nemo-accessibility/pull/18


There is an example of how to execute with partial content of page 
https://github.com/paypal/nemo-accessibility/blob/master/example/dynamicpage.js 

Try running DEBUG=nemo* node example/usingNemoAccessibility.js when aatt is on.

**Comment by rkrjain** [comment]
I will check and get back
